### ISSUE TITLE
[S3] 바텀시트 슬라이드 닫기 기능을 구현한다.

### ISSUE THREAD

**Issue by kyungmim** [TEAM-FLASH/Toucheese-FE#101]
### 📄 Describe
> Story2와 연결된 작업
- 바텀시트 슬라이드 닫기 기능을 구현한다.

### ✅ Tasks
- [x] 바텀 시트 컨텐츠 크기에 따른 동적 높이 수정
- [x] 바텀시트 슬라이드 닫기 기능 구현
- [x] 바텀시트 외의 다른 컨텐츠 클릭시 바텀시트 닫기

### 🙋🏻 More
*No response*
