### ISSUE TITLE
[S3] 리뷰 컴포넌트 고도화 작업을 진행한다.

### ISSUE THREAD

**Issue by woojoung1217** [TEAM-FLASH/Toucheese-FE#114]
### 📄 Describe
- 리뷰 컴포넌트 고도화 작업을 진행한다

### ✅ Tasks
- [x] 리뷰 컴포넌트 고도화
- [x] 리뷰 컴포넌트 코드 스플리팅 및 추상화
- [ ]  겹치는 아이콘 삭제 

### 🙋🏻 More
*No response*
