### ISSUE TITLE
[S3] 이미지 클릭시 딤으로 확대된 사진을 보여준다.

### ISSUE THREAD

**Issue by JWJung-99** [TEAM-FLASH/Toucheese-FE#120]
### 📄 Describe
- 이미지 딤 모달 구현

### ✅ Tasks
- [x] 포트폴리오용 이미지 딤 모달 구현
- [x] 리뷰용 이미지 딤 모달 구현
- [ ] 딤 모달 title 타입 수정

### 🙋🏻 More
*No response*
