### ISSUE TITLE
[S3] 포트폴리오 페이지를 구현한다.

### ISSUE THREAD

**Issue by s0zzang** [TEAM-FLASH/Toucheese-FE#135]
### 📄 Describe
- 포트폴리오 페이지를 구현한다

### ✅ Tasks
- [x] 스튜디오 상세 헤더 호출
- [x] 네비게이션 호출
- [x] 포트폴리오 필터 버튼 : 기욱님 포트폴리오 API 수정 후 착수 가능
- [x] 포트폴리오 데이터 호출
- [x] 포트폴리오 아이템 클릭시 딤 모달 오픈
- [x] 동적 메타 태그 설정

### 🙋🏻 More
*No response*
