### ISSUE TITLE
[S3] 북마크, 상단 탭, 딤 모달 테스트 코드를 작성한다.

### ISSUE THREAD

**Issue by JWJung-99** [TEAM-FLASH/Toucheese-FE#143]
### 📄 Describe
- 테스트 코드 작성

### ✅ Tasks
- [x] 북마크 테스트 코드 작성
- [x] 상단 탭 테스트 코드 작성
- [x] 딤 모달 테스트 코드 작성

### 🙋🏻 More
*No response*
