### ISSUE TITLE
[S3] 메뉴 페이지 QA 진행한다.

### ISSUE THREAD

**Issue by kyungmim** [TEAM-FLASH/Toucheese-FE#162]
### 📄 Describe
- 메뉴 페이지 QA 한다

### ✅ Tasks
- [x] 메뉴 정보 컴포넌트 총 금액 기본값 0으로 수정
- [x] 메뉴 목록 로딩 시 제목 undefined 표출 기본값 ''으로 변경
- [x] 메뉴 목록 BackButton import 제거
- [x] 메뉴 목록 IMenuListRes타입 수정
### 🙋🏻 More
*No response*
