### ISSUE TITLE
[S3] 스튜디오 상세 정보 기능을 구현한다

### ISSUE THREAD

**Issue by HuiseonDev** [TEAM-FLASH/Toucheese-FE#166]
### 📄 Describe
- 스튜디오 정보에서 사용되는 상세정보 기능 구현

### ✅ Tasks
- [x] 매장 소개의 텍스트 더보기 기능을 구현한다
- [x] 영업정보의 정기휴무와 요일별 영업시간 기능을 구현한다
- [x] 매장정보의 옵션 기능을 구현한다

### 🙋🏻 More
*No response*
