### ISSUE TITLE
[S2] 공통 필터 버튼 UI기능을 구현한다.

### ISSUE THREAD

**Issue by HuiseonDev** [TEAM-FLASH/Toucheese-FE#21]
### 📄 Describe
- 공통으로 사용될 필터 버튼ui를 구현한다

### ✅ Tasks
- [x] 바텀시트가 올라오는 필터링 버튼 UI
- [x] 필터링이 초기화 되는 버튼 UI
- [x] 최근 검색어 기록 UI

### 🙋🏻 More
*No response*
