### ISSUE TITLE
[S2] 매장 정보 필터 기능을 구현한다.

### ISSUE THREAD

**Issue by woojoung1217** [TEAM-FLASH/Toucheese-FE#31]
### 📄 Describe
- BookingSearchContainer 구현

### ✅ Tasks
- [x] 레이아웃 및 ui 구현 
- [x] 내부에서 useModal 호출
- [x] 검색으로 갈 수 있는 button 구현
- [x] 테스트 코드 작성

### 🙋🏻 More
*No response*
