### ISSUE TITLE
[S2] 공통 모달(full size)을 구현한다.

### ISSUE THREAD

**Issue by s0zzang** [TEAM-FLASH/Toucheese-FE#9]
### 📄 Describe
- Description

### ✅ Tasks
- [x] 모달을 공통 컴포넌트로 제작한다.
- [x] 전체 페이지 사이즈의 모달을 구현한다.
- [x] 버튼을 클릭하면 모달이 활성화된다.
- [x] 변경된 디자인을 반영한다.

### 🙋🏻 More
*No response*
